#!/bin/bash
set -euo pipefail
# AUTHORED
# Gate: T038 — src/commands/init.ts (MODIFY: Provision ~/.gwrk/plugins/)
# Generated by PE — deterministic vitest gate

test -f src/commands/init.ts || { echo "FAIL: T038 — src/commands/init.ts not found" >&2; exit 1; }

pnpm vitest run src/commands/init.test.ts --reporter=verbose \
  || { echo "FAIL: T038 — vitest failed for src/commands/init.test.ts" >&2; exit 1; }

echo "PASS: T038 — src/commands/init.ts"
