#!/bin/bash
set -euo pipefail
# AUTHORED
# Gate: T039 — src/plugins/migrate.ts (NEW: .agents/ to ~/.gwrk/plugins/ migration)
# Generated by PE — deterministic vitest gate

test -f src/plugins/migrate.ts || { echo "FAIL: T039 — src/plugins/migrate.ts not found" >&2; exit 1; }

pnpm vitest run src/plugins/migrate.test.ts --reporter=verbose \
  || { echo "FAIL: T039 — vitest failed for src/plugins/migrate.test.ts" >&2; exit 1; }

echo "PASS: T039 — src/plugins/migrate.ts"
