#!/bin/bash
set -euo pipefail
# AUTHORED
# Gate: T040 — src/plugins/seed.ts (NEW: Taxonomy to atomic skills seeding)
# Generated by PE — deterministic vitest gate

test -f src/plugins/seed.ts || { echo "FAIL: T040 — src/plugins/seed.ts not found" >&2; exit 1; }

pnpm vitest run src/plugins/seed.test.ts --reporter=verbose \
  || { echo "FAIL: T040 — vitest failed for src/plugins/seed.test.ts" >&2; exit 1; }

echo "PASS: T040 — src/plugins/seed.ts"
