#!/bin/bash
set -euo pipefail
# AUTHORED
# Gate: T041 — src/commands/init.test.ts (test file for init provisioning)
# Generated by PE — deterministic vitest gate

test -f src/commands/init.test.ts || { echo "FAIL: T041 — src/commands/init.test.ts not found" >&2; exit 1; }

pnpm vitest run src/commands/init.test.ts --reporter=verbose \
  || { echo "FAIL: T041 — vitest failed for src/commands/init.test.ts" >&2; exit 1; }

echo "PASS: T041 — src/commands/init.test.ts"
