#!/bin/bash
set -euo pipefail
# AUTHORED
# Gate: T042 — Phase 7 test strategy (all test files pass)
# Generated by PE — deterministic vitest gate

pnpm vitest run src/commands/init.test.ts --reporter=verbose \
  || { echo "FAIL: T042 — init.test.ts failed" >&2; exit 1; }

pnpm vitest run src/plugins/migrate.test.ts --reporter=verbose \
  || { echo "FAIL: T042 — migrate.test.ts failed" >&2; exit 1; }

pnpm vitest run src/plugins/seed.test.ts --reporter=verbose \
  || { echo "FAIL: T042 — seed.test.ts failed" >&2; exit 1; }

echo "PASS: T042 — Phase 7 test strategy complete"
