/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

// src/engine/pulse.test.ts
// RED test file for 006-pulse Phase 1 + Phase 3
// Generated by /define-tests workflow
import { beforeEach, describe, expect, it, vi } from "vitest";
import {
  bucketByWeek,
  generatePulseReport,
  parseGitLog,
  scanRepository,
  scanSpecProgress,
} from "./pulse.js"; // RED — module does not exist yet
import type { PulseSnapshot, WeeklyBucket } from "./types.js";
import { PulseSnapshotSchema } from "./types.js";

vi.mock("../utils/git.js", () => ({
  gitLog: vi.fn(() => ""),
  detectDefaultBranch: vi.fn(() => "main"),
  gitBranches: vi.fn(() => []),
  gitLineCount: vi.fn(() => 0),
  gitDraftLineCount: vi.fn(() => 0),
  gitMainCommits: vi.fn(() => new Set()),
}));

// ─── Phase 1 Tests ───────────────────────────────────────────────

describe("FR-002/FR-004: parseGitLog", () => {
  it("TR-001: parses git log --numstat output into ParsedCommit array", () => {
    // US-002 acceptance scenario 1 (data extraction)
    const raw = [
      "abc1234|2026-01-06T10:00:00Z",
      "15\t3\tsrc/foo.ts",
      "8\t0\tsrc/bar.ts",
      "",
      "def5678|2026-01-13T14:30:00Z",
      "5\t10\tsrc/baz.ts",
      "",
    ].join("\n");

    const commits = parseGitLog(raw);

    expect(commits).toHaveLength(2);
    expect(commits[0].hash).toBe("abc1234");
    expect(commits[0].timestamp).toBe("2026-01-06T10:00:00Z");
    expect(commits[0].files).toHaveLength(2);
    expect(commits[0].files[0]).toEqual({
      added: 15,
      deleted: 3,
      path: "src/foo.ts",
    });
    expect(commits[1].hash).toBe("def5678");
    expect(commits[1].files[0].deleted).toBe(10);
  });

  it("TR-001: handles empty git log output", () => {
    const commits = parseGitLog("");

    expect(commits).toEqual([]);
  });

  it("TR-001: handles binary files (- - path format)", () => {
    const raw = [
      "abc1234|2026-01-06T10:00:00Z",
      "-\t-\timage.png",
      "10\t0\tsrc/code.ts",
      "",
    ].join("\n");

    const commits = parseGitLog(raw);

    expect(commits).toHaveLength(1);
    // Binary files should be skipped or have 0/0
    expect(commits[0].files.length).toBeGreaterThanOrEqual(1);
  });

  it("rejects: malformed commit line without separator", () => {
    const raw = "not-a-valid-commit-line\n10\t0\tsrc/foo.ts\n";

    // Should either skip malformed entries or throw
    const commits = parseGitLog(raw);
    expect(commits).toHaveLength(0);
  });
});

describe("FR-004: bucketByWeek", () => {
  it("TR-001: groups commits into ISO-week buckets", () => {
    // US-004 acceptance scenario 1
    // Commits in 3 different weeks
    const commits = [
      {
        hash: "a1",
        timestamp: "2026-01-06T10:00:00Z", // Week 2 (Mon Jan 6)
        files: [{ added: 100, deleted: 0, path: "src/a.ts" }],
      },
      {
        hash: "a2",
        timestamp: "2026-01-08T10:00:00Z", // Week 2 (Wed Jan 8)
        files: [{ added: 50, deleted: 10, path: "src/b.ts" }],
      },
      {
        hash: "b1",
        timestamp: "2026-01-13T10:00:00Z", // Week 3 (Mon Jan 13)
        files: [{ added: 30, deleted: 5, path: "src/c.ts" }],
      },
      {
        hash: "c1",
        timestamp: "2026-01-20T10:00:00Z", // Week 4 (Mon Jan 20)
        files: [{ added: 20, deleted: 15, path: "src/d.ts" }],
      },
    ];

    const buckets = bucketByWeek(commits, new Set(["a1", "a2", "b1", "c1"]));

    expect(buckets.length).toBeGreaterThanOrEqual(3);

    // Verify each bucket has required fields
    for (const bucket of buckets) {
      expect(bucket).toHaveProperty("weekStart");
      expect(bucket).toHaveProperty("totalMain");
      expect(bucket).toHaveProperty("added");
      expect(bucket).toHaveProperty("deleted");
      // Validate structural contract
      expect(typeof bucket.weekStart).toBe("string");
      expect(typeof bucket.totalMain).toBe("number");
    }

    // Verify sorted oldest-first
    for (let i = 1; i < buckets.length; i++) {
      expect(buckets[i].weekStart >= buckets[i - 1].weekStart).toBe(true);
    }

    // Week 2 should have added=150 (100+50), deleted=10
    const week2 = buckets[0];
    expect(week2.added).toBe(150);
    expect(week2.deleted).toBe(10);
  });

  it("TR-001: returns empty array for no commits", () => {
    const buckets = bucketByWeek([], new Set());

    expect(buckets).toEqual([]);
  });
});

describe("FR-003: Published/Draft LOC separation", () => {
  it("TR-002: scanRepository separates mainLoc vs draftLoc", () => {
    // US-003 acceptance scenario 1
    // Given a repo with 100 LOC on main and 50 LOC on feature/foo
    // This test will need mocking — scanRepository calls git helpers

    // Since scanRepository uses real git calls, we mock at the git helper level
    // For RED state, we just want to verify the contract shape
    const snapshot: PulseSnapshot = {
      repoPath: "/tmp/test-repo",
      repoName: "test-repo",
      defaultBranch: "main",
      scannedAt: new Date().toISOString(),
      mainLoc: 100,
      draftLoc: 50,
      weeklyBuckets: [],
    };

    // Validate shape against Zod schema
    expect(() => PulseSnapshotSchema.parse(snapshot)).not.toThrow();
    expect(snapshot.mainLoc).toBe(100);
    expect(snapshot.draftLoc).toBe(50);
    expect(snapshot.mainLoc).not.toBe(snapshot.draftLoc);
  });
});

// ─── Phase 3 Tests ───────────────────────────────────────────────

describe("FR-005: scanSpecProgress", () => {
  it("TR-008: counts spec.md and plan.md files in specs directory", () => {
    // US-005 acceptance scenario 1
    const fs = require("node:fs");
    vi.spyOn(fs, "existsSync").mockReturnValue(true);
    vi.spyOn(fs, "readdirSync").mockReturnValue([
      { isDirectory: () => true, name: "001-cli-core" },
      { isDirectory: () => true, name: "002-build-server" },
    ] as any);

    // Mock individual file checks
    vi.spyOn(fs, "existsSync").mockImplementation((p: string) => {
      if (p.includes("specs/001-cli-core/spec.md")) return true;
      if (p.includes("specs/001-cli-core/plan.md")) return true;
      if (p.includes("specs/002-build-server/spec.md")) return true;
      if (p.includes("specs/002-build-server/plan.md")) return false;
      if (p.endsWith("specs")) return true;
      return false;
    });

    const result = scanSpecProgress("/tmp/mock-project");

    expect(result.totalSpecs).toBe(2);
    expect(result.totalPlans).toBe(1);
    
    vi.restoreAllMocks();
  });

  it("rejects: returns zero counts for non-existent specs directory", () => {
    const fs = require("node:fs");
    vi.spyOn(fs, "existsSync").mockReturnValue(false);

    const result = scanSpecProgress("/tmp/no-specs-here");

    expect(result.totalSpecs).toBe(0);
    expect(result.totalPlans).toBe(0);
    
    vi.restoreAllMocks();
  });
});

describe("FR-001: generatePulseReport multi-repo aggregation", () => {
  it("TR-004: aggregates PulseSnapshots from multiple repos", () => {
    // US-001 acceptance scenario 1
    const mockConfig = {
      project: { name: "test" },
      agents: { define: "gemini" as const, implement: "codex-cloud" as const },
      pulse: { repos: ["/tmp/repo-a", "/tmp/repo-b"] },
    };

    const fs = require("node:fs");
    vi.spyOn(fs, "existsSync").mockReturnValue(true);
    vi.spyOn(fs, "readdirSync").mockReturnValue([]);

    const report = generatePulseReport(mockConfig);

    expect(report.repositories).toHaveLength(2);
    expect(report.repositories[0].repoName).toBe("repo-a");
    expect(report.repositories[1].repoName).toBe("repo-b");

    vi.restoreAllMocks();
  });

  it("rejects: throws when pulse.repos is empty (FR-001 error state)", () => {
    // US-001 acceptance scenario 2
    const mockConfig = {
      project: { name: "test" },
      agents: { define: "gemini" as const, implement: "codex-cloud" as const },
      pulse: { repos: [] },
    };

    expect(() => generatePulseReport(mockConfig)).toThrow(
      /No repositories tracked/,
    );
  });
});
