// src/engine/pulse-integration.test.ts
// RED integration test for 006-pulse Phase 1
// Generated by /define-tests workflow
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { scanRepository } from "./pulse.js"; // RED — module does not exist yet
import { PulseSnapshotSchema } from "./types.js"; // RED — module does not exist yet

describe("TR-007: Integration test — real git repo", () => {
  let repoDir: string;

  beforeAll(() => {
    // Create a real temp git repo with commits across 3 weeks
    repoDir = fs.mkdtempSync(path.join(os.tmpdir(), "pulse-integration-"));

    execSync("git init", { cwd: repoDir });
    execSync('git config user.email "test@test.com"', { cwd: repoDir });
    execSync('git config user.name "Test"', { cwd: repoDir });

    // Week 1: Jan 6, 2026 (Monday)
    fs.writeFileSync(
      path.join(repoDir, "file1.ts"),
      'export const a = "hello";\nexport const b = "world";\n',
    );
    execSync("git add -A", { cwd: repoDir });
    execSync(
      'GIT_AUTHOR_DATE="2026-01-06T10:00:00Z" GIT_COMMITTER_DATE="2026-01-06T10:00:00Z" git commit -m "week 1: initial"',
      { cwd: repoDir, shell: "/bin/bash" },
    );

    // Week 2: Jan 13, 2026 (Monday)
    fs.writeFileSync(
      path.join(repoDir, "file2.ts"),
      'export const c = "foo";\nexport const d = "bar";\nexport const e = "baz";\n',
    );
    execSync("git add -A", { cwd: repoDir });
    execSync(
      'GIT_AUTHOR_DATE="2026-01-13T10:00:00Z" GIT_COMMITTER_DATE="2026-01-13T10:00:00Z" git commit -m "week 2: add file2"',
      { cwd: repoDir, shell: "/bin/bash" },
    );

    // Week 3: Jan 20, 2026 (Monday)
    fs.writeFileSync(
      path.join(repoDir, "file3.ts"),
      'export const f = "qux";\n',
    );
    // Also modify file1 to test add/delete tracking
    fs.writeFileSync(
      path.join(repoDir, "file1.ts"),
      'export const a = "hello updated";\n',
    );
    execSync("git add -A", { cwd: repoDir });
    execSync(
      'GIT_AUTHOR_DATE="2026-01-20T10:00:00Z" GIT_COMMITTER_DATE="2026-01-20T10:00:00Z" git commit -m "week 3: add file3, modify file1"',
      { cwd: repoDir, shell: "/bin/bash" },
    );

    // Create a feature branch with draft work
    execSync("git checkout -b feature/draft", { cwd: repoDir });
    fs.writeFileSync(
      path.join(repoDir, "draft.ts"),
      'export const draft = "wip";\nexport const draft2 = "wip2";\n',
    );
    execSync("git add -A", { cwd: repoDir });
    execSync(
      'GIT_AUTHOR_DATE="2026-01-21T10:00:00Z" GIT_COMMITTER_DATE="2026-01-21T10:00:00Z" git commit -m "draft: wip"',
      { cwd: repoDir, shell: "/bin/bash" },
    );

    // Return to main
    execSync("git checkout main", { cwd: repoDir });
  });

  afterAll(() => {
    fs.rmSync(repoDir, { recursive: true, force: true });
  });

  it("VR-001: scans real repo and produces valid PulseSnapshot", () => {
    // US-002 acceptance scenario 1
    const snapshot = scanRepository(repoDir);

    // Validate against Zod schema
    expect(() => PulseSnapshotSchema.parse(snapshot)).not.toThrow();

    // Basic shape assertions
    expect(snapshot.repoPath).toBe(repoDir);
    expect(snapshot.defaultBranch).toBe("main");
    expect(snapshot.scannedAt).toBeTruthy();
  });

  it("VR-001: weekly buckets span 3+ weeks", () => {
    // US-004 acceptance scenario 1
    const snapshot = scanRepository(repoDir);

    expect(snapshot.weeklyBuckets.length).toBeGreaterThanOrEqual(3);

    // Each bucket has required fields
    for (const bucket of snapshot.weeklyBuckets) {
      expect(bucket).toHaveProperty("weekStart");
      expect(bucket).toHaveProperty("totalMain");
      expect(bucket).toHaveProperty("added");
      expect(bucket).toHaveProperty("deleted");
    }
  });

  it("VR-001: mainLoc is positive (repo has content on main)", () => {
    // US-003 — published LOC
    const snapshot = scanRepository(repoDir);

    expect(snapshot.mainLoc).toBeGreaterThan(0);
  });

  it("VR-001: draftLoc is positive (repo has content on feature branch)", () => {
    // US-003 — draft LOC
    const snapshot = scanRepository(repoDir);

    expect(snapshot.draftLoc).toBeGreaterThan(0);
  });

  it("VR-004: determinism — two scans produce identical output", () => {
    // TC-001 — same git history, same output
    const snapshot1 = scanRepository(repoDir);
    const snapshot2 = scanRepository(repoDir);

    // Ignore scannedAt (timestamp will differ)
    const withoutTimestamp = (s: typeof snapshot1) => {
      const { scannedAt, ...rest } = s;
      return rest;
    };

    expect(withoutTimestamp(snapshot1)).toEqual(withoutTimestamp(snapshot2));
  });
});

describe("FR-002: Error handling for invalid paths", () => {
  it("VR-002: throws for non-git-repo path", () => {
    // US-002 acceptance scenario 2
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "not-a-repo-"));

    try {
      expect(() => scanRepository(tempDir)).toThrow(/Not a git repository/);
    } finally {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  });

  it("FR-002 error state: throws for non-existent path", () => {
    expect(() => scanRepository("/tmp/path-does-not-exist-xyz")).toThrow(
      /Path not found/,
    );
  });
});
