import fs from "node:fs";
import path from "node:path";
import type { EffortReport } from "./types.js";

/**
 * Writes the EffortReport object to a markdown assessment document.
 * Returns the absolute path of the generated file.
 */
export function writeEffortReport(report: EffortReport, outputDir: string): string {
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const d = new Date(report.generatedAt);
  const dateStr = d.toISOString().split("T")[0];
  const filename = `effort-${report.featureId}-${dateStr}.md`;
  const filePath = path.join(outputDir, filename);

  let md = `# Effort Assessment: ${report.featureId}\n\n`;
  md += `**Generated**: ${d.toLocaleString()}\n`;
  md += `**Overhead Factor**: ${report.overheadFactor}×\n\n`;

  md += "## Executive Summary\n\n";
  md += `- **Total Story Points**: ${report.totalSP}\n`;
  md += `- **Total Raw Hours**: ${report.totalRawHours}h\n`;
  md += `- **Total Forecast (incl. OH)**: **${report.totalWithOverhead}h** (${report.totalDays} days)\n\n`;

  md += "## Role Breakdown\n\n";
  md += "| Role | Name | SP | Rate (h/SP) | Raw (h) | Forecast (h) | Days |\n";
  md += "|---|---|---|---|---|---|---|\n";

  for (const rb of report.roles) {
    if (rb.spAssigned === 0) continue;
    md += `| ${rb.role} | ${rb.roleName} | ${rb.spAssigned} | ${rb.hoursPerSP} | ${rb.rawHours} | ${rb.withOverhead} | ${rb.days} |\n`;
  }
  md += "\n";

  md += "## Story Breakdown\n\n";
  md += "| ID | Title | SP | Roles | Forecast (h) |\n";
  md += "|---|---|---|---|---|\n";

  let unestimatedExist = false;
  for (const st of report.stories) {
    if (st.sp === 0 || st.roles.length === 0) {
      unestimatedExist = true;
    }
    const rolesStr = st.roles.length > 0 ? st.roles.join(", ") : "UNESTIMATED";
    const spStr = st.sp === 0 ? "UNESTIMATED" : st.sp.toString();
    md += `| ${st.storyId} | ${st.title} | ${spStr} | ${rolesStr} | ${st.withOverhead} |\n`;
  }
  md += "\n";

  if (unestimatedExist) {
    md += "> **Warning**: Some stories are marked as unestimated (missing SP or Roles). These are excluded from the forecast totals.\n\n";
  }

  md += "## Methodology\n";
  md += "This report was auto-generated by the GWRK Effort Engine via \`gwrk effort\`. ";
  md += "Story Points (SP) are assigned to User Stories in \`spec.md\`. Each role parses its allocated SP times the configured hourly rate (Base). ";
  md += `The Base is then multiplied by the Overhead Factor (${report.overheadFactor}×) to produce the final Forecast.\n`;

  fs.writeFileSync(filePath, md, "utf-8");
  return filePath;
}
