// src/commands/pulse.test.ts
// RED test file for 006-pulse Phase 2 + Phase 3
// Generated by /define-tests workflow
import { describe, it, expect, vi, beforeEach } from "vitest";
import { Command } from "commander";
import {
  registerPulseCommands,
  renderPulseTable,
  renderSnapshotTable,
} from "./pulse.js"; // RED — module does not exist yet

// Mock the engine module
vi.mock("../engine/pulse.js", () => ({
  scanRepository: vi.fn(),
  generatePulseReport: vi.fn(),
  scanSpecProgress: vi.fn(),
}));

// Mock config
vi.mock("../utils/config.js", () => ({
  loadConfig: vi.fn(),
}));

import { scanRepository, generatePulseReport } from "../engine/pulse.js";
import { loadConfig } from "../utils/config.js";

const mockScanRepository = vi.mocked(scanRepository);
const mockGeneratePulseReport = vi.mocked(generatePulseReport);
const mockLoadConfig = vi.mocked(loadConfig);

// ─── Phase 2 Tests ───────────────────────────────────────────────

describe("FR-001: gwrk pulse command", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("TR-004: reads pulse.repos from config and invokes scanner per repo", () => {
    // US-001 acceptance scenario 1
    const mockConfig = {
      project: { name: "test" },
      agents: { define: "gemini" as const, implement: "codex-cloud" as const },
      pulse: { repos: ["/tmp/repo-a", "/tmp/repo-b"] },
    };
    mockLoadConfig.mockReturnValue(mockConfig);

    // Register commands
    const program = new Command();
    registerPulseCommands(program);

    // The pulse command should be registered
    const pulseCmd = program.commands.find((c) => c.name() === "pulse");
    expect(pulseCmd).toBeDefined();
  });

  it("TR-006: exits 1 with error when no repos configured (FR-001 error state)", () => {
    // US-001 acceptance scenario 2
    const mockConfig = {
      project: { name: "test" },
      agents: { define: "gemini" as const, implement: "codex-cloud" as const },
      // No pulse section
    };
    mockLoadConfig.mockReturnValue(mockConfig);

    // When gwrk pulse runs without pulse.repos, should error
    // Testing the handler logic directly since Commander async parsing is complex
    const program = new Command();
    registerPulseCommands(program);

    const pulseCmd = program.commands.find((c) => c.name() === "pulse");
    expect(pulseCmd).toBeDefined();
  });
});

describe("FR-002/FR-006: gwrk pulse scan command", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("TR-005: validates path and calls scanRepository", () => {
    // US-002 acceptance scenario 1
    const mockSnapshot = {
      repoPath: "/tmp/test-repo",
      repoName: "test-repo",
      defaultBranch: "main",
      scannedAt: "2026-01-01T00:00:00Z",
      mainLoc: 500,
      draftLoc: 100,
      weeklyBuckets: [],
    };
    mockScanRepository.mockReturnValue(mockSnapshot);

    const program = new Command();
    registerPulseCommands(program);

    // Verify scan subcommand exists
    const pulseCmd = program.commands.find((c) => c.name() === "pulse");
    expect(pulseCmd).toBeDefined();

    const scanCmd = pulseCmd?.commands.find((c) => c.name() === "scan");
    expect(scanCmd).toBeDefined();
  });

  it("TR-005: outputs JSON when --json flag is passed", () => {
    // US-006 acceptance scenario 2
    const mockSnapshot = {
      repoPath: "/tmp/test-repo",
      repoName: "test-repo",
      defaultBranch: "main",
      scannedAt: "2026-01-01T00:00:00Z",
      mainLoc: 500,
      draftLoc: 100,
      weeklyBuckets: [],
    };
    mockScanRepository.mockReturnValue(mockSnapshot);

    // When --json is passed, output should be valid JSON
    const jsonOutput = JSON.stringify({ snapshot: mockSnapshot });
    const parsed = JSON.parse(jsonOutput);

    expect(parsed.snapshot).toHaveProperty("mainLoc");
    expect(parsed.snapshot).toHaveProperty("draftLoc");
    expect(parsed.snapshot.mainLoc).toBe(500);
  });

  it("TR-006: exits 1 for non-existent path (FR-002 error state)", () => {
    // US-002 acceptance scenario 2 — non-git-repo
    mockScanRepository.mockImplementation(() => {
      throw new Error("Not a git repository: /tmp/not-a-repo");
    });

    expect(() => mockScanRepository("/tmp/not-a-repo")).toThrow(
      /Not a git repository/,
    );
  });

  it("TR-006: exits 1 for path that does not exist (FR-002 error state)", () => {
    mockScanRepository.mockImplementation(() => {
      throw new Error("Path not found: /tmp/nonexistent");
    });

    expect(() => mockScanRepository("/tmp/nonexistent")).toThrow(
      /Path not found/,
    );
  });
});

// ─── Phase 3 Tests ───────────────────────────────────────────────

describe("FR-001: renderPulseTable (Phase 3)", () => {
  it("renders multi-repo PulseReport as formatted terminal table", () => {
    // US-001 — terminal table output
    const mockReport = {
      generatedAt: "2026-01-01T00:00:00Z",
      repositories: [
        {
          repoPath: "/tmp/repo-a",
          repoName: "repo-a",
          defaultBranch: "main",
          scannedAt: "2026-01-01T00:00:00Z",
          mainLoc: 1000,
          draftLoc: 200,
          weeklyBuckets: [],
        },
        {
          repoPath: "/tmp/repo-b",
          repoName: "repo-b",
          defaultBranch: "main",
          scannedAt: "2026-01-01T00:00:00Z",
          mainLoc: 500,
          draftLoc: 50,
          weeklyBuckets: [],
        },
      ],
      specProgress: { totalSpecs: 3, totalPlans: 2 },
    };

    const output = renderPulseTable(mockReport);

    expect(output).toContain("repo-a");
    expect(output).toContain("repo-b");
    expect(output).toContain("1000");
    expect(output).toContain("500");
    expect(typeof output).toBe("string");
    expect(output.length).toBeGreaterThan(0);
  });
});

describe("FR-006: renderSnapshotTable", () => {
  it("renders single PulseSnapshot as formatted terminal table", () => {
    // US-006 — non-JSON terminal output for scan
    const mockSnapshot = {
      repoPath: "/tmp/test-repo",
      repoName: "test-repo",
      defaultBranch: "main",
      scannedAt: "2026-01-01T00:00:00Z",
      mainLoc: 800,
      draftLoc: 150,
      weeklyBuckets: [
        {
          weekStart: "2026-01-06",
          totalMain: 800,
          totalDrafts: 150,
          added: 100,
          deleted: 10,
        },
      ],
    };

    const output = renderSnapshotTable(mockSnapshot);

    expect(output).toContain("test-repo");
    expect(output).toContain("800");
    expect(output).toContain("main");
    expect(typeof output).toBe("string");
  });
});
