import { Command } from "commander";
// src/commands/pulse.test.ts
// RED test file for 006-pulse Phase 2 + Phase 3
// Generated by /define-tests workflow
import { beforeEach, describe, expect, it, vi } from "vitest";
import {
  registerPulseCommands,
  renderPulseTable,
  renderSnapshotTable,
} from "./pulse.js"; // RED — module does not exist yet

// Mock the engine module
vi.mock("../engine/pulse.js", () => ({
  scanRepository: vi.fn(),
  generatePulseReport: vi.fn(),
  scanSpecProgress: vi.fn(),
}));

// Mock config
vi.mock("../utils/config.js", () => ({
  loadConfig: vi.fn(),
}));

import { generatePulseReport, scanRepository } from "../engine/pulse.js";
import { loadConfig } from "../utils/config.js";

const mockScanRepository = vi.mocked(scanRepository);
const mockGeneratePulseReport = vi.mocked(generatePulseReport);
const mockLoadConfig = vi.mocked(loadConfig);

// ─── Phase 2 Tests ───────────────────────────────────────────────

describe("FR-001: gwrk measure pulse command", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.spyOn(console, "log").mockImplementation(() => {});
  });

  it("TR-004: reads pulse.repos from config and invokes scanner per repo", async () => {
    // US-001 acceptance scenario 1
    const mockConfig = {
      project: { name: "test" },
      agents: { define: "gemini" as const, implement: "codex-cloud" as const },
      pulse: { repos: ["/tmp/repo-a", "/tmp/repo-b"] },
    };
    mockLoadConfig.mockReturnValue(mockConfig);

    const mockReport = {
      generatedAt: new Date().toISOString(),
      repositories: [],
      specProgress: { totalSpecs: 0, totalPlans: 0 },
    };
    mockGeneratePulseReport.mockReturnValue(mockReport);

    // Register commands
    const program = new Command();
    program.exitOverride(); 
    program.enablePositionalOptions();
    const measure = program.command("measure");
    registerPulseCommands(measure);

    await program.parseAsync(["measure", "pulse"], { from: "user" });

    expect(mockLoadConfig).toHaveBeenCalled();
    expect(mockGeneratePulseReport).toHaveBeenCalledWith(mockConfig);
    expect(console.log).toHaveBeenCalled();
  });

  it("TR-006: exits with error when no repos configured (FR-001 error state)", async () => {
    // US-001 acceptance scenario 2
    const mockConfig = {
      project: { name: "test" },
      agents: { define: "gemini" as const, implement: "codex-cloud" as const },
      pulse: { repos: [] },
    };
    mockLoadConfig.mockReturnValue(mockConfig);
    mockGeneratePulseReport.mockImplementation(() => {
      throw new Error("No repositories tracked");
    });

    const program = new Command();
    program.exitOverride();
    program.enablePositionalOptions();
    const measure = program.command("measure");
    registerPulseCommands(measure);

    await program.parseAsync(["measure", "pulse"], { from: "user" });
    expect(process.exitCode).toBe(1);
    process.exitCode = 0; 
  });
});

describe("FR-002/FR-006: gwrk measure pulse scan command", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.spyOn(console, "log").mockImplementation(() => {});
  });

  it("TR-005: validates path and calls scanRepository", async () => {
    // US-002 acceptance scenario 1
    const mockSnapshot = {
      repoPath: "/tmp/test-repo",
      repoName: "test-repo",
      defaultBranch: "main",
      scannedAt: "2026-01-01T00:00:00Z",
      mainLoc: 500,
      draftLoc: 100,
      weeklyBuckets: [],
    };
    mockScanRepository.mockReturnValue(mockSnapshot);

    const fs = require("node:fs");
    vi.spyOn(fs, "existsSync").mockReturnValue(true);

    const program = new Command();
    program.exitOverride();
    program.enablePositionalOptions();
    const measure = program.command("measure");
    registerPulseCommands(measure);

    await program.parseAsync(["measure", "pulse", "scan", "/tmp/test-repo"], { from: "user" });

    expect(mockScanRepository).toHaveBeenCalledWith(expect.stringContaining("test-repo"), undefined);
    expect(console.log).toHaveBeenCalled();
  });

  it("TR-005: outputs JSON when --json flag is passed", async () => {
    // US-006 acceptance scenario 2
    const mockSnapshot = {
      repoPath: "/tmp/test-repo",
      repoName: "test-repo",
      defaultBranch: "main",
      scannedAt: "2026-01-01T00:00:00Z",
      mainLoc: 500,
      draftLoc: 100,
      weeklyBuckets: [],
    };
    mockScanRepository.mockReturnValue(mockSnapshot);
    const fs = require("node:fs");
    vi.spyOn(fs, "existsSync").mockReturnValue(true);

    const program = new Command();
    program.exitOverride();
    program.enablePositionalOptions();
    const measure = program.command("measure");
    registerPulseCommands(measure);

    await program.parseAsync(["measure", "pulse", "scan", "/tmp/test-repo", "--json"], { from: "user" });

    expect(console.log).toHaveBeenCalledWith(
      expect.stringContaining('"repoName": "test-repo"')
    );
  });
});

// ─── Phase 3 Tests ───────────────────────────────────────────────

describe("FR-001: renderPulseTable (Phase 3)", () => {
  it("renders multi-repo PulseReport as formatted terminal table", () => {
    // US-001 — terminal table output
    const mockReport = {
      generatedAt: "2026-01-01T00:00:00Z",
      repositories: [
        {
          repoPath: "/tmp/repo-a",
          repoName: "repo-a",
          defaultBranch: "main",
          scannedAt: "2026-01-01T00:00:00Z",
          mainLoc: 1000,
          draftLoc: 200,
          weeklyBuckets: [],
        },
        {
          repoPath: "/tmp/repo-b",
          repoName: "repo-b",
          defaultBranch: "main",
          scannedAt: "2026-01-01T00:00:00Z",
          mainLoc: 500,
          draftLoc: 50,
          weeklyBuckets: [],
        },
      ],
      specProgress: { totalSpecs: 3, totalPlans: 2 },
    };

    const output = renderPulseTable(mockReport);

    expect(output).toContain("repo-a");
    expect(output).toContain("repo-b");
    expect(output).toContain("1000");
    expect(output).toContain("500");
    expect(typeof output).toBe("string");
    expect(output.length).toBeGreaterThan(0);
  });
});

describe("FR-006: renderSnapshotTable", () => {
  it("renders single PulseSnapshot as formatted terminal table", () => {
    // US-006 — non-JSON terminal output for scan
    const mockSnapshot = {
      repoPath: "/tmp/test-repo",
      repoName: "test-repo",
      defaultBranch: "main",
      scannedAt: "2026-01-01T00:00:00Z",
      mainLoc: 800,
      draftLoc: 150,
      weeklyBuckets: [
        {
          weekStart: "2026-01-06",
          totalMain: 800,
          totalDrafts: 150,
          added: 100,
          deleted: 10,
        },
      ],
    };

    const output = renderSnapshotTable(mockSnapshot);

    expect(output).toContain("test-repo");
    expect(output).toContain("800");
    expect(output).toContain("main");
    expect(typeof output).toBe("string");
  });
});
