import fs from "node:fs";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { tasksGenerateCommand } from "./tasks-generate.js";

/**
 * RED tests for --reconcile behavior.
 * These cover known scenarios:
 *   1. Preserves completed task status when title matches
 *   2. New tasks from updated plan appear as "open"
 *   3. Removed tasks from updated plan are marked "cancelled"
 *   4. Task IDs are reassigned sequentially (no gaps)
 *   5. generatedFrom.plan.hash is updated to current plan
 */
describe("gwrk define tasks --reconcile", () => {
  const tempDir = path.join(process.cwd(), "temp-test-reconcile");

  function writePlan(content: string) {
    const specsDir = path.join(tempDir, "specs", "test-feature");
    fs.mkdirSync(specsDir, { recursive: true });
    fs.writeFileSync(path.join(specsDir, "plan.md"), content);
    // ADR-005 §8.4 guard requires gap-matrix.md (generated by define tests)
    if (!fs.existsSync(path.join(specsDir, "gap-matrix.md"))) {
      fs.writeFileSync(path.join(specsDir, "gap-matrix.md"), "| AC | Test File |\n|----|-----------|\n");
    }
    // Strict Gate Authoring requirement
    fs.mkdirSync(path.join(specsDir, "contracts"), { recursive: true });
    fs.writeFileSync(path.join(specsDir, "contracts", "mock.md"), "# Contract");
  }

  function readTasks(): Record<string, unknown> {
    const tasksPath = path.join(
      tempDir,
      "specs",
      "test-feature",
      ".gwrk",
      "tasks.json",
    );
    return JSON.parse(fs.readFileSync(tasksPath, "utf-8"));
  }

  const PLAN_V1 = `# Implementation Plan: test-feature

### Phase 1: Setup

**Files (2):**
- \`src/config.ts\` (NEW: Configuration module)
- \`src/utils.ts\` (NEW: Utility helpers)

#### Done When
- Config loads
`;

  const PLAN_V2 = `# Implementation Plan: test-feature

### Phase 1: Setup

**Files (3):**
- \`src/config.ts\` (NEW: Configuration module)
- \`src/logger.ts\` (NEW: Logging system)
- \`src/utils.ts\` (NEW: Utility helpers)

#### Done When
- Config loads
- Logger initializes
`;

  const PLAN_V3_REMOVED = `# Implementation Plan: test-feature

### Phase 1: Setup

**Files (1):**
- \`src/logger.ts\` (NEW: Logging system)

#### Done When
- Logger initializes
`;

  beforeEach(() => {
    if (fs.existsSync(tempDir)) {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
    fs.mkdirSync(tempDir, { recursive: true });
    // Provide a mock standard config to satisfy loadConfig
    fs.writeFileSync(path.join(tempDir, ".gwrkrc.json"), JSON.stringify({ project: { name: "test-feature" }, agents: { define: "gemini", implement: "gemini" } }));
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
    vi.restoreAllMocks();
  });

  // RED: --reconcile not yet implemented. Convert back to it() when reconcile lands.
  it.todo("preserves completed task status when title matches");

  it.todo("adds new tasks from updated plan as open");

  it.todo("marks removed tasks as cancelled");

  it.todo("updates generatedFrom hash to current plan");
});
