/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

// src/utils/git.test.ts
// RED test file for 006-pulse Phase 1 — Git shell helpers
// Generated by /define-tests workflow
import { beforeEach, describe, expect, it, vi } from "vitest";
import {
  detectDefaultBranch,
  gitBranches,
  gitLineCount,
  gitLog,
} from "./git.js"; // RED — module does not exist yet

// Mock child_process
vi.mock("node:child_process", () => ({
  execFileSync: vi.fn(),
}));

import { execFileSync } from "node:child_process";
const mockExecFileSync = vi.mocked(execFileSync);

describe("FR-008: Default branch auto-detection", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("US-008 scenario 1: detects main via symbolic-ref", () => {
    // Given a repo where symbolic-ref returns refs/remotes/origin/main
    mockExecFileSync.mockReturnValueOnce(
      Buffer.from("refs/remotes/origin/main\n"),
    );

    const result = detectDefaultBranch("/tmp/test-repo");

    expect(result).toBe("main");
  });

  it("US-008 scenario 2: detects master via symbolic-ref", () => {
    // Given a repo where symbolic-ref returns refs/remotes/origin/master
    mockExecFileSync.mockReturnValueOnce(
      Buffer.from("refs/remotes/origin/master\n"),
    );

    const result = detectDefaultBranch("/tmp/test-repo");

    expect(result).toBe("master");
  });

  it("US-008 fallback: falls back to main when symbolic-ref fails but main exists", () => {
    // Given symbolic-ref fails (no remote)
    mockExecFileSync.mockImplementationOnce(() => {
      throw new Error(
        "fatal: ref refs/remotes/origin/HEAD is not a symbolic ref",
      );
    });
    // Given git branch lists main
    mockExecFileSync.mockReturnValueOnce(
      Buffer.from("* main\n  feature/foo\n"),
    );

    const result = detectDefaultBranch("/tmp/test-repo");

    expect(result).toBe("main");
  });

  it("US-008 fallback: falls back to master when symbolic-ref fails and main absent", () => {
    // Given symbolic-ref fails
    mockExecFileSync.mockImplementationOnce(() => {
      throw new Error(
        "fatal: ref refs/remotes/origin/HEAD is not a symbolic ref",
      );
    });
    // Given git branch does NOT list main, but lists master
    mockExecFileSync.mockReturnValueOnce(
      Buffer.from("* master\n  feature/bar\n"),
    );

    const result = detectDefaultBranch("/tmp/test-repo");

    expect(result).toBe("master");
  });

  it("rejects: throws when no known default branch found (FR-008 error state)", () => {
    // Given symbolic-ref fails
    mockExecFileSync.mockImplementationOnce(() => {
      throw new Error("fatal");
    });
    // Given git branch lists only feature branches
    mockExecFileSync.mockReturnValueOnce(
      Buffer.from("  feature/foo\n  feature/bar\n"),
    );

    expect(() => detectDefaultBranch("/tmp/test-repo")).toThrow(
      /Cannot detect default branch/,
    );
  });
});

describe("FR-002: gitLog returns raw git log output", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns raw string from git log --numstat", () => {
    const mockOutput =
      "abc123|2026-01-01T00:00:00Z\n10\t0\tsrc/foo.ts\n\ndef456|2026-01-02T00:00:00Z\n5\t3\tsrc/bar.ts\n";
    mockExecFileSync.mockReturnValueOnce(Buffer.from(mockOutput));

    const result = gitLog("/tmp/test-repo");

    expect(result).toBe(mockOutput);
    expect(result).toContain("abc123");
    expect(result).toContain("def456");
  });

  it("rejects: throws when path is not a git repository", () => {
    mockExecFileSync.mockImplementationOnce(() => {
      throw new Error("fatal: not a git repository");
    });

    expect(() => gitLog("/tmp/not-a-repo")).toThrow();
  });
});

describe("FR-002: gitBranches lists repository branches", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns array of branch names", () => {
    mockExecFileSync.mockReturnValueOnce(
      Buffer.from("* main\n  feature/foo\n  feature/bar\n"),
    );

    const result = gitBranches("/tmp/test-repo");

    expect(result).toContain("main");
    expect(result).toContain("feature/foo");
    expect(result.length).toBeGreaterThanOrEqual(2);
  });
});

describe("FR-003: gitLineCount counts lines at a ref", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns line count as number", () => {
    // Mock git ls-files output piped to wc -l
    mockExecFileSync.mockReturnValueOnce(Buffer.from("1523\n"));

    const result = gitLineCount("/tmp/test-repo", "main");

    expect(result).toBe(1523);
    expect(typeof result).toBe("number");
  });

  it("returns 0 for empty repository", () => {
    mockExecFileSync.mockReturnValueOnce(Buffer.from("0\n"));

    const result = gitLineCount("/tmp/test-repo", "main");

    expect(result).toBe(0);
  });
});
